# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "sr_mod"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e5857819-6b25-4abb-b7af-2ff923b99fa5";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/d14de13e-6780-4a53-9d60-af82aafd37b2"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
